Changes to suppoer Genesis Plus GX and Stella cores
JesseTG/libretro.py pull request #9
Opened 2024-09-02 01:11 UTC by JSensebe

Added 16-bit pixel format and rotation support  to ArrayVideoDriver.screenshot(). Added buffer reallocation when necessary to ArrayVideoDriver.refresh(). Added check when setting geometry before av_info is filled in MultiVideoDriver.

2024-09-03 17:26 UTC, JesseTG requested changes
Looks good overall, just a few things I'd appreciate some clarity on.

2024-09-03 17:26 UTC, JesseTG commented on src/libretro/drivers/video/software/array.py
> +                is_sideways = True
Doesn't your logic here assume a pixel size of 4 bytes? Or is that just for the output buffer?

2024-09-03 17:26 UTC, JesseTG commented on src/libretro/drivers/video/driver.py
> +    def screenshot(self, prerotate: bool = True) -> Screenshot | None:
Could you add details about this parameter to the doc comment, please?

2024-09-04 00:09 UTC, JSensebe commented on src/libretro/drivers/video/software/array.py
> +                is_sideways = True
It's just the output buffer. I'll add some comments to make the code clearer.

2024-09-04 01:36 UTC, merged